# Nombre de la aplicaci\u00c3\u00b3n
spring.application.name=Essencia Fit

# Conexi\u00c3\u00b3n a PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/suplementos}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

# Configuraci\u00c3\u00b3n JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update   
spring.jpa.show-sql=true             
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false         
# Puerto del servidor 
server.port=${PORT}
# --- JWT CONFIG ---
jwt.secret=CAMBIA_ESTA_CLAVE_A_UNA_MUY_LARGA_32CARACTERES_MINIMO_!@#123abcXYZ
jwt.expirationMs=3600000  

